- name: Template systemd service unit
  template:
    src: netflow-dumper-flow-tools.service.j2
    dest: /etc/systemd/system/netflow-dumper-flow-tools-{{ item.name }}.service
  register: p


- name: Create flows directory
  file:
    path: "{{ item['flows_dir'] }}"
    state: directory


- name: Start and enable service for {{ item.name }}
  systemd:
    name: netflow-dumper-flow-tools-{{ item.name }}
    state: restarted
    enabled: yes
  when: p is changed

