---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install collector packages
  package:
    name: "{{ lookup('vars', 'netflow_dumper_' ~ item ~ '_packages') }}"
  loop: "{{ netflow_dumper_instances | map(attribute='collector') | list | unique }}"

- name: Create config dir
  file:
    path: "{{ netflow_dumper_conf_dir }}"
    state: directory

- name: Run tasks for pmacct
  include_tasks: pmacct.yaml
  when: netflow_dumper_instances | selectattr('collector', 'eq', 'pmacct') | list
  
- name: Run tasks for nfdump
  include_tasks: nfdump.yaml
  when: netflow_dumper_instances | selectattr('collector', 'eq', 'nfdump') | list

- name: Run tasks for flow-tools
  include_tasks: flow-tools.yaml
  when: netflow_dumper_instances | selectattr('collector', 'eq', 'flow_tools') | list
