- name: Template pmacct configs for {{ item.name }}
  template:
    src: "nfacctd.conf.j2"
    dest: "{{ netflow_dumper_conf_dir }}/{{ item.name }}.conf"
#  loop: "{{ netflow_dumper_instances | selectattr('collector', 'eq', 'pmacct') | list }}"


- name: Setup pmacct service instance for {{ item.name }}
  systemd:
    daemon_reload: yes
    name: "netflow-dumper-pmacct@{{ item.name }}"
    state: started
    enabled: yes
#  loop: "{{ netflow_dumper_instances | selectattr('collector', 'eq', 'pmacct') | list }}"
