- name: Template pmacct systemd service file
  template:
    src: netflow-dumper-pmacct@.service
    dest: /etc/systemd/system/netflow-dumper-pmacct@.service

- name: Run tasks for pmacct
  include_tasks: pmacct_instance.yaml
  loop: "{{ netflow_dumper_instances | selectattr('collector', 'eq', 'pmacct') | list }}"
